# games.meta.sh
# All game URLs + pretty card metadata used by setup_lan_arcade.sh

# ---------- Game source URLs ----------
# folder_name => source URL (or special flag like ZIP_GITHUB_REPO)
declare -A GAMES=(
  # Educational / typing
  ["typing-test"]="ZIP_GITHUB_REPO"
  ["balloon-pop-maths"]="https://richardhenyash.github.io/balloon-pop-maths/"
  ["IdleAnt"]="https://scorzy.github.io/IdleAnt/"

  # Idle JS collection
  ["solaris"]="https://idle-js-games.github.io/solaris/"
  ["goomyclicker"]="https://idle-js-games.github.io/goomyclicker/"
  ["watercompany"]="https://idle-js-games.github.io/WaterCompany/"
  ["electric-clicker"]="https://idle-js-games.github.io/Electric-Clicker/"
  ["idle-traveller"]="https://idle-js-games.github.io/idle-traveller/"
  ["devlife"]="https://idle-js-games.github.io/devlife/"
  ["level13"]="https://idle-js-games.github.io/level13/"
  ["BuildASpaceShip"]="https://idle-js-games.github.io/BuildASpaceShip/"
  ["CSGOClicker"]="https://idle-js-games.github.io/CSGOClicker/"
  ["particle-clicker"]="https://idle-js-games.github.io/particle-clicker/"
  ["second-derivative-clicker"]="https://idle-js-games.github.io/Second-Derivative-Clicker-game/"
  ["confectionery-collector"]="https://idle-js-games.github.io/Confectionery-Collector-incr-game/"
  ["cityclicker"]="https://idle-js-games.github.io/cityclicker-johntoopublic-incr-game/"
  ["koutoftimer-idle-miner"]="https://idle-js-games.github.io/koutoftimer-idle-miner/"
  ["incremental-kaloyanz"]="https://idle-js-games.github.io/Incremental-KaloyanZ-/"
  ["dolla_idle_game"]="https://idle-js-games.github.io/dolla_idle_game/"
  ["citygame-clicker"]="https://idle-js-games.github.io/citygame-clicker/"
  ["realmofdecay"]="https://idle-js-games.github.io/RealmOfDecay-incr-game/"
  ["racing-clicker"]="https://idle-js-games.github.io/racing-clicker-idle-game/"
  ["space-idle"]="https://idle-js-games.github.io/space-idle-Commkeen/"
  ["santas-workshop"]="https://idle-js-games.github.io/santas-workshop/"
  ["idlepunk"]="https://idle-js-games.github.io/idlepunk/"
  ["cookieclicker"]="https://idle-js-games.github.io/cookieclicker/"
  ["c64clicker"]="https://idle-js-games.github.io/c64clicker/"
  ["goomyclicker2"]="https://idle-js-games.github.io/goomyClicker2/"
  ["incremental-rpg"]="https://idle-js-games.github.io/IncrementalRPG/"
  ["fallen-warrior"]="https://idle-js-games.github.io/Legend-of-the-Fallen-Warrior-rpg/"
  ["idlecraft"]="https://idle-js-games.github.io/idlecraft/"
  ["sandcastle-builder"]="https://idle-js-games.github.io/Sandcastle-Builder-clicker/"
  ["farm-clicker"]="https://idle-js-games.github.io/farm-clicker/"
  ["technomancy"]="https://idle-js-games.github.io/Technomancy/Technomancy/"
  ["happyking"]="https://idle-js-games.github.io/happyking/"
  ["incremancer"]="https://idle-js-games.github.io/incremancer/"
    # Classics / arcade
  ["hextris"]="https://hextris.github.io/hextris/"
  ["2048"]="https://gabrielecirulli.github.io/2048/"
  ["tetris"]="https://jdiemke.github.io/tetris/"
  ["floppybird"]="https://nebezb.com/floppybird/"
  ["pacman"]="https://pacman.platzh1rsch.ch/"
  ["snake"]="https://icethecoder.github.io/snake/"
    ["supertasball"]="https://supertasball.amos.me/"

)

# ---------- Pretty card metadata ----------
# folder_name => "Title|Icon|META line|Description|Tag1,Tag2[,Tag3]"
declare -A GAME_INFO=(
  ["typing-test"]="Typing Test|⌨️|Typing · Speed Test|Simple browser-based typing test to measure words per minute and accuracy over short runs.|Skill,WPM trainer"
  ["balloon-pop-maths"]="Balloon Pop Maths|🎈|Maths · Educational|Kid-friendly balloon popping maths game with multiple difficulty modes.|Kids,Maths practice"
  ["IdleAnt"]="Idle Ant|🐜|Colony · Incremental|Grow an ant colony: buy units, unlock research, and scale into absurd production.|Ants,Colony,Long haul"

  ["solaris"]="Solaris|☀️|Space · Idle|Grow a sci-fi colony, harvest resources and expand across the system.|Space,Colony"
  ["goomyclicker"]="Goomy Clicker|🐌|Clicker · Cute|Click for goomies, buy upgrades and watch numbers climb.|Clicker,Casual"
  ["watercompany"]="Water Company|💧|Utility · Incremental|Build a water empire, upgrade pumps and scale output like a true tycoon.|Tycoon,Utility"
  ["electric-clicker"]="Electric Clicker|⚡|Energy · Idle|Generate power, upgrade production and build a massive energy network.|Energy,Upgrades"
  ["idle-traveller"]="Idle Traveller|🌍|Exploration · Incremental|Travel the world, unlock destinations and boost your traveller XP.|World,Adventure idle"
  ["devlife"]="Devlife|💻|Coding · Simulation|Live the programmer grind: code, ship features, buy upgrades, repeat.|Coding,Life sim"
  ["level13"]="Level 13|📜|Text Adventure · Idle|Story-driven incremental with strange events and mysterious upgrades.|Narrative,Mystery"
  ["BuildASpaceShip"]="Build A Spaceship|🛠️|Space · Upgrades|Collect parts, improve your ship and journey deeper into space.|Space,Builder"
  ["CSGOClicker"]="CSGO Clicker|🔫|Loot · Upgrade spam|Open cases, collect skins and upgrade your gear with clicker mechanics.|Loot boxes,Fast idle"
  ["particle-clicker"]="Particle Clicker|⚛️|Physics · Idle|CERN-inspired incremental where you smash particles for science.|Science,Idle clicker"
  ["second-derivative-clicker"]="Second Derivative|➗|Math · Incremental|A maths-inspired incremental where calculus becomes exponential growth.|Math,Abstract idle"
  ["confectionery-collector"]="Confectionery Collector|🍬|Sugar · Idle|Build a candy empire with sugary upgrades and sweet production chains.|Candy,Cute idle"
  ["cityclicker"]="City Clicker|🏙️|City Builder · Idle|Start from a tiny town and grow it into a sprawling metropolis.|City building,Upgrades"
  ["koutoftimer-idle-miner"]="Idle Miner|⛏️|Mining · Progressive|Dig deeper, mine faster and automate systems to speed up income.|Mining,Automation"
  ["incremental-kaloyanz"]="Incremental KaloyanZ|👆|Classic Idle · Simple|Minimalist incremental with clean progression and simple upgrades.|Minimalist,Clicker"
  ["dolla_idle_game"]="Dolla Idle Game|💵|Money · Incremental|Stack dollars, unlock multipliers and grow a financial empire.|Money,Simple idle"
  ["citygame-clicker"]="CityGame Clicker|🏘️|Urban · Builder idle|Another city-building incremental where you expand neighbourhoods and population.|Builder,Idle city"
  ["realmofdecay"]="Realm of Decay|💀|Fantasy · Dark idle|Raise undead armies, upgrade dark powers and consume kingdoms.|Dark fantasy,RPG idle"
  ["racing-clicker"]="Racing Clicker|🏎️|Racing · Upgrade idle|Upgrade your ride, race for cash and push your top speed ever higher.|Cars,Speed grind"
  ["space-idle"]="Space Idle|🛰️|Sci-fi · Idle|Build an interstellar economy, mine asteroids and expand into space.|Space,Progression"
  ["santas-workshop"]="Santa's Workshop|🎄|Seasonal · Idle|Manage elves, make toys and upgrade the workshop in this festive incremental.|Holiday,Idle"
  ["idlepunk"]="IdlePunk|🤖|Cyberpunk · Idle|Upgrade your neon city and automate a dystopian empire.|Cyberpunk,Idle"
  ["cookieclicker"]="Cookie Clicker Clone|🍪|Classic · Clicker|Bake cookies, buy upgrades and scale an obscene bakery empire.|Classic,Clicker"
  ["c64clicker"]="C64 Clicker|🖥️|Retro · Idle|Retro-themed incremental that feels like using a Commodore 64.|Retro,Clicker"
  ["goomyclicker2"]="Goomy Clicker 2|✨|Clicker · Cute|A shinier sequel to Goomy Clicker with more upgrades and chaos.|Clicker,Casual"
  ["incremental-rpg"]="Incremental RPG|⚔️|Idle · RPG|Fight, level up, upgrade gear and repeat in a simple incremental RPG.|RPG,Idle"
  ["fallen-warrior"]="Fallen Warrior|🗡️|RPG · Idle|Battle waves of enemies and upgrade your warrior over time.|RPG,Progression"
  ["idlecraft"]="IdleCraft|⛏️|Crafting · Idle|Mine, craft and refine in a blocky factory-style idle game.|Craft,Idle"
  ["sandcastle-builder"]="Sandcastle Builder|🏖️|Clicker · Idle|Build sandcastles, gather materials and expand a sandy empire.|Classic,Incremental"
  ["farm-clicker"]="Farm Clicker|🌾|Farming · Idle clicker|Plant crops, harvest and upgrade your farm in classic idle style.|Casual,Idle clicker"
  ["technomancy"]="Technomancy|🔮|Tech tree · Incremental|Research technologies and unlock a sprawling chain of systems.|Tech tree,Incremental"
  ["happyking"]="Happy King|👑|Kingdom · Idle management|Rule a tiny kingdom, juggle resources and keep your realm thriving.|Kingdom sim,Light management"
  ["incremancer"]="Incremancer|🧟|Zombie idle · Necromancer|Raise the dead, send zombie hordes and grow a necromancer empire.|Zombie horde,Clicker idle"
  ["hextris"]="Hextris|🧩|Puzzle · Arcade|Fast, addictive hexagon puzzle inspired by Tetris.|Puzzle,Arcade,Mobile-friendly"
  ["2048"]="2048|🔢|Puzzle · Swipe|Combine tiles to reach 2048 (and keep going). Great on phones/tablets.|Puzzle,Swipe,Classic"
  ["tetris"]="Tetris|🧱|Arcade · Classic|Clean browser Tetris clone with keyboard controls.|Classic,Arcade,Skill"
  ["floppybird"]="Floppy Bird|🐤|Arcade · Tap/Space|Flappy-bird-style rage game. Tap/click/space to fly.|Mobile-friendly,Arcade,Reflex"
  ["pacman"]="Pac-Man|🟡|Arcade · Maze|Classic Pac-Man remake in HTML5 (includes sound).|Classic,Arcade,Mobile-friendly"
  ["snake"]="Snake|🐍|Arcade · Classic|Simple Snake with smooth movement (great on touch devices).|Classic,Mobile-friendly,Quick play"
  ["supertasball"]="Super TASball|🎱|Pinball · Idle|Open-source pinball idle game where you “program” shots and build up your run over time.|Pinball,Idle,Strategy"

)
