# games.meta.sh
# All game URLs + pretty card metadata used by setup_lan_arcade.sh

# ---------- Game source URLs ----------
# folder_name => source URL (or special flag like ZIP_GITHUB_REPO / ZIP_GITHUB_FILE)
declare -A GAMES=(
  # Educational / typing
  ["typing-test"]="ZIP_GITHUB_REPO"
  ["balloon-pop-maths"]="ZIP_GITHUB_REPO::richardhenyash/balloon-pop-maths::master"
  ["edukiz"]="ZIP_GITHUB_REPO::timmalich/edukiz_live::main"
  ["set-sizes-animals"]="ZIP_GITHUB_FILE::jkanev/educational-html-games::master::set-sizes-animals.html"
  ["set-sizes-shapes"]="ZIP_GITHUB_FILE::jkanev/educational-html-games::master::set-sizes-shapes.html"
  ["triple-number-memory"]="ZIP_GITHUB_FILE::jkanev/educational-html-games::master::triple-number-memory.html"
  ["game-of-sums"]="ZIP_GITHUB_FILE::jkanev/educational-html-games::master::game-of-sums.html"
  ["game-of-differences"]="ZIP_GITHUB_FILE::jkanev/educational-html-games::master::game-of-differences.html"
  ["game-of-triplets"]="ZIP_GITHUB_FILE::jkanev/educational-html-games::master::game-of-triplets.html"
  ["hangman-reading"]="https://ravichandranjv.github.io/Hangman/"
  ["wordsearch-reading"]="https://wanderingstan.github.io/wordsearch/"
  ["sudoku"]="https://sudoku.tn1ck.com/"
  ["crossword-puzzle-maker"]="https://papauschek.github.io/crossword-puzzle-maker/"
  ["crossword-classic"]="ZIP_GITHUB_REPO::deepakshajan/Crossword-Puzzle::master"
  ["IdleAnt"]="https://scorzy.github.io/IdleAnt/"

  # Idle JS collection
  ["solaris"]="https://idle-js-games.github.io/solaris/"
  ["goomyclicker"]="https://idle-js-games.github.io/goomyclicker/"
  ["watercompany"]="https://idle-js-games.github.io/WaterCompany/"
  ["electric-clicker"]="https://idle-js-games.github.io/Electric-Clicker/"
  ["idle-traveller"]="https://idle-js-games.github.io/idle-traveller/"
  ["devlife"]="https://idle-js-games.github.io/devlife/"
  ["level13"]="https://idle-js-games.github.io/level13/"
  ["BuildASpaceShip"]="https://idle-js-games.github.io/BuildASpaceShip/"
  ["CSGOClicker"]="https://idle-js-games.github.io/CSGOClicker/"
  ["particle-clicker"]="https://idle-js-games.github.io/particle-clicker/"
  ["second-derivative-clicker"]="GIT_GITHUB_REPO::idle-js-games/Second-Derivative-Clicker-game::master"
  ["confectionery-collector"]="ZIP_GITHUB_REPO::idle-js-games/Confectionery-Collector-incr-game::master"
  ["cityclicker"]="https://idle-js-games.github.io/cityclicker-johntoopublic-incr-game/"
  ["koutoftimer-idle-miner"]="https://idle-js-games.github.io/koutoftimer-idle-miner/"
  ["incremental-kaloyanz"]="https://idle-js-games.github.io/Incremental-KaloyanZ-/"
  ["dolla_idle_game"]="https://idle-js-games.github.io/dolla_idle_game/"
  ["citygame-clicker"]="https://idle-js-games.github.io/citygame-clicker/"
  ["realmofdecay"]="https://idle-js-games.github.io/RealmOfDecay-incr-game/"
  ["racing-clicker"]="https://idle-js-games.github.io/racing-clicker-idle-game/"
  ["space-idle"]="https://idle-js-games.github.io/space-idle-Commkeen/"
  ["santas-workshop"]="https://idle-js-games.github.io/santas-workshop/"
  ["idlepunk"]="https://idle-js-games.github.io/idlepunk/"
  ["cookieclicker"]="ZIP_GITHUB_REPO::idle-js-games/cookieclicker::gh-pages"
  ["c64clicker"]="https://idle-js-games.github.io/c64clicker/"
  ["goomyclicker2"]="https://idle-js-games.github.io/goomyClicker2/"
  ["incremental-rpg"]="https://idle-js-games.github.io/IncrementalRPG/"
  ["fallen-warrior"]="ZIP_GITHUB_REPO::idle-js-games/Legend-of-the-Fallen-Warrior-rpg::master"
  ["idlecraft"]="https://idle-js-games.github.io/idlecraft/"
  ["sandcastle-builder"]="https://idle-js-games.github.io/Sandcastle-Builder-clicker/"
  ["farm-clicker"]="https://idle-js-games.github.io/farm-clicker/"
  ["technomancy"]="https://idle-js-games.github.io/Technomancy/Technomancy/"
  ["happyking"]="https://idle-js-games.github.io/happyking/"
  ["incremancer"]="https://idle-js-games.github.io/incremancer/"
    # Classics / arcade
  ["hextris"]="https://hextris.github.io/hextris/"
  ["2048"]="https://gabrielecirulli.github.io/2048/"
  ["tetris"]="https://jdiemke.github.io/tetris/"
  ["floppybird"]="https://nebezb.com/floppybird/"
  ["pacman"]="https://pacman.platzh1rsch.ch/"
  ["snake"]="https://icethecoder.github.io/snake/"
    ["supertasball"]="https://supertasball.amos.me/"
  ["outpost-siege"]="LOCAL_DIR::local-games/outpost-siege"
  ["breachline-tactics"]="LOCAL_DIR::local-games/breachline-tactics"
  ["circuit-foundry"]="LOCAL_DIR::local-games/circuit-foundry"
  ["lan-tank-arena"]="LOCAL_DIR::local-games/lan-tank-arena"

)

# ---------- Pretty card metadata ----------
# folder_name => "Title|Icon|META line|Description|Tag1,Tag2[,Tag3]"
declare -A GAME_INFO=(
  ["typing-test"]="Typing Test|⌨️|Typing · Speed Test|Simple browser-based typing test to measure words per minute and accuracy over short runs.|Skill,WPM trainer"
  ["balloon-pop-maths"]="Balloon Pop Maths|🎈|Maths · Educational|Kid-friendly balloon popping maths game with multiple difficulty modes.|Kids,Maths practice"
  ["edukiz"]="Edukiz Kids Suite|BOOK|Educational - Maths/Letters|Open-source educational mini-game suite with number, letter, and early arithmetic activities for children.|Kids,Maths,Letters"
  ["set-sizes-animals"]="Set Sizes (Animals)|PAWS|Maths - Number Sense|Estimate group sizes quickly without counting in an animal-themed number sense game.|Number sense,Quick maths,Kids"
  ["set-sizes-shapes"]="Set Sizes (Shapes)|SHAPES|Maths - Number Sense|Fast shape-counting challenge that trains visual quantity recognition and early maths fluency.|Visual maths,Kids,Quick play"
  ["triple-number-memory"]="Triple Number Memory|CARDS|Maths - Memory|Match number triplets across digits, symbols, and words to build memory and number understanding.|Memory,Numbers,English"
  ["game-of-sums"]="Game of Sums|PLUS|Maths - Mental Arithmetic|Two-player arithmetic duel where players build valid addition equations from limited number cards.|Addition,Strategy,Classroom"
  ["game-of-differences"]="Game of Differences|MINUS|Maths - Mental Arithmetic|Subtraction-focused variant of the equation duel, designed for fast mental maths practice.|Subtraction,Strategy,Classroom"
  ["game-of-triplets"]="Game of Triplets|TRIPLE|Maths - Equation Builder|Build full equations from numbers and operators to score points in a deeper arithmetic strategy game.|Equations,Logic,Strategy"
  ["hangman-reading"]="Hangman Reading|HANG|Reading - Vocabulary|Classic hangman word-guessing game that reinforces spelling and vocabulary recall.|Vocabulary,Spelling,English"
  ["wordsearch-reading"]="Word Search|WORDS|Reading - Word Hunt|Find hidden words in a grid to build scanning speed, vocabulary, and pattern recognition.|Word hunt,English,Puzzle"
  ["sudoku"]="Sudoku|SUDOKU|Puzzle - Logic & Numbers|Classic Sudoku logic puzzle for number placement and reasoning practice.|Logic,Maths,Brain training"
  ["crossword-puzzle-maker"]="Crossword Puzzle Maker|CROSS|Reading - Crossword Builder|Build and play crossword puzzles in the browser for vocabulary and clue-solving practice.|Crossword,English,Classroom"
  ["crossword-classic"]="Crossword Classic|CLUE|Reading - Crossword Puzzle|Classic crossword puzzle gameplay with clues and grid entry mechanics.|Crossword,English,Wordplay"
  ["IdleAnt"]="Idle Ant|🐜|Colony · Incremental|Grow an ant colony: buy units, unlock research, and scale into absurd production.|Ants,Colony,Long haul"

  ["solaris"]="Solaris|☀️|Space · Idle|Grow a sci-fi colony, harvest resources and expand across the system.|Space,Colony"
  ["goomyclicker"]="Goomy Clicker|🐌|Clicker · Cute|Click for goomies, buy upgrades and watch numbers climb.|Clicker,Casual"
  ["watercompany"]="Water Company|💧|Utility · Incremental|Build a water empire, upgrade pumps and scale output like a true tycoon.|Tycoon,Utility"
  ["electric-clicker"]="Electric Clicker|⚡|Energy · Idle|Generate power, upgrade production and build a massive energy network.|Energy,Upgrades"
  ["idle-traveller"]="Idle Traveller|🌍|Exploration · Incremental|Travel the world, unlock destinations and boost your traveller XP.|World,Adventure idle"
  ["devlife"]="Devlife|💻|Coding · Simulation|Live the programmer grind: code, ship features, buy upgrades, repeat.|Coding,Life sim"
  ["level13"]="Level 13|📜|Text Adventure · Idle|Story-driven incremental with strange events and mysterious upgrades.|Narrative,Mystery"
  ["BuildASpaceShip"]="Build A Spaceship|🛠️|Space · Upgrades|Collect parts, improve your ship and journey deeper into space.|Space,Builder"
  ["CSGOClicker"]="CSGO Clicker|🔫|Loot · Upgrade spam|Open cases, collect skins and upgrade your gear with clicker mechanics.|Loot boxes,Fast idle"
  ["particle-clicker"]="Particle Clicker|⚛️|Physics · Idle|CERN-inspired incremental where you smash particles for science.|Science,Idle clicker"
  ["second-derivative-clicker"]="Second Derivative|➗|Math · Incremental|A maths-inspired incremental where calculus becomes exponential growth.|Math,Abstract idle"
  ["confectionery-collector"]="Confectionery Collector|🍬|Sugar · Idle|Build a candy empire with sugary upgrades and sweet production chains.|Candy,Cute idle"
  ["cityclicker"]="City Clicker|🏙️|City Builder · Idle|Start from a tiny town and grow it into a sprawling metropolis.|City building,Upgrades"
  ["koutoftimer-idle-miner"]="Idle Miner|⛏️|Mining · Progressive|Dig deeper, mine faster and automate systems to speed up income.|Mining,Automation"
  ["incremental-kaloyanz"]="Incremental KaloyanZ|👆|Classic Idle · Simple|Minimalist incremental with clean progression and simple upgrades.|Minimalist,Clicker"
  ["dolla_idle_game"]="Dolla Idle Game|💵|Money · Incremental|Stack dollars, unlock multipliers and grow a financial empire.|Money,Simple idle"
  ["citygame-clicker"]="CityGame Clicker|🏘️|Urban · Builder idle|Another city-building incremental where you expand neighbourhoods and population.|Builder,Idle city"
  ["realmofdecay"]="Realm of Decay|💀|Fantasy · Dark idle|Raise undead armies, upgrade dark powers and consume kingdoms.|Dark fantasy,RPG idle"
  ["racing-clicker"]="Racing Clicker|🏎️|Racing · Upgrade idle|Upgrade your ride, race for cash and push your top speed ever higher.|Cars,Speed grind"
  ["space-idle"]="Space Idle|🛰️|Sci-fi · Idle|Build an interstellar economy, mine asteroids and expand into space.|Space,Progression"
  ["santas-workshop"]="Santa's Workshop|🎄|Seasonal · Idle|Manage elves, make toys and upgrade the workshop in this festive incremental.|Holiday,Idle"
  ["idlepunk"]="IdlePunk|🤖|Cyberpunk · Idle|Upgrade your neon city and automate a dystopian empire.|Cyberpunk,Idle"
  ["cookieclicker"]="Cookie Clicker Clone|🍪|Classic · Clicker|Bake cookies, buy upgrades and scale an obscene bakery empire.|Classic,Clicker"
  ["c64clicker"]="C64 Clicker|🖥️|Retro · Idle|Retro-themed incremental that feels like using a Commodore 64.|Retro,Clicker"
  ["goomyclicker2"]="Goomy Clicker 2|✨|Clicker · Cute|A shinier sequel to Goomy Clicker with more upgrades and chaos.|Clicker,Casual"
  ["incremental-rpg"]="Incremental RPG|⚔️|Idle · RPG|Fight, level up, upgrade gear and repeat in a simple incremental RPG.|RPG,Idle"
  ["fallen-warrior"]="Fallen Warrior|🗡️|RPG · Idle|Battle waves of enemies and upgrade your warrior over time.|RPG,Progression"
  ["idlecraft"]="IdleCraft|⛏️|Crafting · Idle|Mine, craft and refine in a blocky factory-style idle game.|Craft,Idle"
  ["sandcastle-builder"]="Sandcastle Builder|🏖️|Clicker · Idle|Build sandcastles, gather materials and expand a sandy empire.|Classic,Incremental"
  ["farm-clicker"]="Farm Clicker|🌾|Farming · Idle clicker|Plant crops, harvest and upgrade your farm in classic idle style.|Casual,Idle clicker"
  ["technomancy"]="Technomancy|🔮|Tech tree · Incremental|Research technologies and unlock a sprawling chain of systems.|Tech tree,Incremental"
  ["happyking"]="Happy King|👑|Kingdom · Idle management|Rule a tiny kingdom, juggle resources and keep your realm thriving.|Kingdom sim,Light management"
  ["incremancer"]="Incremancer|🧟|Zombie idle · Necromancer|Raise the dead, send zombie hordes and grow a necromancer empire.|Zombie horde,Clicker idle"
  ["hextris"]="Hextris|🧩|Puzzle · Arcade|Fast, addictive hexagon puzzle inspired by Tetris.|Puzzle,Arcade,Mobile-friendly"
  ["2048"]="2048|🔢|Puzzle · Swipe|Combine tiles to reach 2048 (and keep going). Great on phones/tablets.|Puzzle,Swipe,Classic"
  ["tetris"]="Tetris|🧱|Arcade · Classic|Clean browser Tetris clone with keyboard controls.|Classic,Arcade,Skill"
  ["floppybird"]="Floppy Bird|🐤|Arcade · Tap/Space|Flappy-bird-style rage game. Tap/click/space to fly.|Mobile-friendly,Arcade,Reflex"
  ["pacman"]="Pac-Man|🟡|Arcade · Maze|Classic Pac-Man remake in HTML5 (includes sound).|Classic,Arcade,Mobile-friendly"
  ["snake"]="Snake|🐍|Arcade · Classic|Simple Snake with smooth movement (great on touch devices).|Classic,Mobile-friendly,Quick play"
  ["supertasball"]="Super TASball|🎱|Pinball · Idle|Open-source pinball idle game where you “program” shots and build up your run over time.|Pinball,Idle,Strategy"
  ["outpost-siege"]="Outpost Siege|FORT|Tower Defense · Strategy|Original LAN Arcade base defense game with waves, tower upgrades, enemy armor, boss waves, touch controls, and local save progress.|Tower defense,Strategy,Offline original"
  ["breachline-tactics"]="Breachline Tactics|GRID|Tactical Roguelite|Original turn-based squad tactics game with grid combat, operator abilities, enemy turns, room depth, and local best-depth saves.|Tactical,Roguelite,Offline original"
  ["circuit-foundry"]="Circuit Foundry|GEAR|Factory Automation|Original mini automation game where extractors, belts, smelters, generators, and assemblers build a circuit pipeline.|Factory,Automation,Offline original"
  ["lan-tank-arena"]="LAN Tank Arena|TANK|Multiplayer · Arena Combat|Original real-time LAN tank battle with room codes, shared WebSocket state, powerups, respawns, and 2-8 player skirmishes.|Multiplayer,Tank battle,LAN original"

)

# ---------- Category metadata ----------
# folder_name => comma-separated category slugs
# Age categories:
#   - age-5-plus
#   - age-10-plus
#   - age-13-plus
declare -A GAME_CATEGORIES=(
  ["typing-test"]="educational,english,typing,age-10-plus,family"
  ["balloon-pop-maths"]="educational,maths,age-5-plus,family,casual"
  ["edukiz"]="educational,maths,english,typing,age-5-plus,family"
  ["set-sizes-animals"]="educational,maths,age-5-plus,family,casual"
  ["set-sizes-shapes"]="educational,maths,age-5-plus,family,casual"
  ["triple-number-memory"]="educational,maths,english,puzzle,age-5-plus,family"
  ["game-of-sums"]="educational,maths,english,puzzle,strategy,age-10-plus,family"
  ["game-of-differences"]="educational,maths,english,puzzle,strategy,age-10-plus,family"
  ["game-of-triplets"]="educational,maths,english,puzzle,strategy,age-10-plus,family"
  ["hangman-reading"]="educational,english,puzzle,age-10-plus,family"
  ["wordsearch-reading"]="educational,english,puzzle,age-5-plus,family"
  ["sudoku"]="puzzle,maths,strategy,age-10-plus,family"
  ["crossword-puzzle-maker"]="educational,english,puzzle,age-10-plus,family"
  ["crossword-classic"]="educational,english,puzzle,age-10-plus,family"
  ["IdleAnt"]="idle,strategy,management,age-10-plus"

  ["solaris"]="idle,space,strategy,age-10-plus"
  ["goomyclicker"]="clicker,idle,casual,age-5-plus"
  ["watercompany"]="idle,management,simulation,age-10-plus"
  ["electric-clicker"]="idle,clicker,simulation,science,age-10-plus"
  ["idle-traveller"]="idle,adventure,casual,age-10-plus"
  ["devlife"]="simulation,idle,strategy,age-13-plus"
  ["level13"]="idle,adventure,strategy,age-13-plus"
  ["BuildASpaceShip"]="idle,space,strategy,age-10-plus"
  ["CSGOClicker"]="clicker,idle,age-13-plus"
  ["particle-clicker"]="educational,science,idle,clicker,age-10-plus"
  ["second-derivative-clicker"]="educational,maths,idle,age-13-plus"
  ["confectionery-collector"]="idle,clicker,casual,age-5-plus"
  ["cityclicker"]="idle,city-builder,management,age-10-plus"
  ["koutoftimer-idle-miner"]="idle,strategy,management,age-10-plus"
  ["incremental-kaloyanz"]="idle,clicker,casual,age-10-plus"
  ["dolla_idle_game"]="idle,clicker,management,age-10-plus"
  ["citygame-clicker"]="idle,city-builder,management,age-10-plus"
  ["realmofdecay"]="idle,fantasy,rpg,strategy,age-13-plus"
  ["racing-clicker"]="idle,clicker,racing,age-10-plus"
  ["space-idle"]="idle,space,strategy,age-10-plus"
  ["santas-workshop"]="idle,seasonal,management,family,age-5-plus"
  ["idlepunk"]="idle,simulation,strategy,age-13-plus"
  ["cookieclicker"]="idle,clicker,casual,age-5-plus"
  ["c64clicker"]="idle,clicker,retro,age-10-plus"
  ["goomyclicker2"]="idle,clicker,casual,age-5-plus"
  ["incremental-rpg"]="idle,rpg,fantasy,age-10-plus"
  ["fallen-warrior"]="idle,rpg,fantasy,age-10-plus"
  ["idlecraft"]="idle,simulation,strategy,age-10-plus"
  ["sandcastle-builder"]="idle,clicker,casual,family,age-5-plus"
  ["farm-clicker"]="idle,clicker,casual,simulation,age-5-plus"
  ["technomancy"]="idle,science,strategy,age-13-plus"
  ["happyking"]="idle,management,strategy,simulation,age-10-plus"
  ["incremancer"]="idle,fantasy,strategy,age-13-plus"
  ["hextris"]="puzzle,arcade,mobile-friendly,age-10-plus"
  ["2048"]="puzzle,maths,mobile-friendly,age-5-plus"
  ["tetris"]="arcade,puzzle,retro,age-10-plus"
  ["floppybird"]="arcade,casual,mobile-friendly,age-5-plus"
  ["pacman"]="arcade,retro,mobile-friendly,age-5-plus"
  ["snake"]="arcade,retro,mobile-friendly,age-5-plus"
  ["supertasball"]="idle,strategy,arcade,age-10-plus"
  ["outpost-siege"]="tower-defense,strategy,arcade,simulation,mobile-friendly,age-10-plus"
  ["breachline-tactics"]="tactical,roguelite,strategy,arcade,mobile-friendly,age-10-plus"
  ["circuit-foundry"]="factory,automation,strategy,simulation,management,mobile-friendly,age-10-plus"
  ["lan-tank-arena"]="multiplayer,action,arcade,strategy,mobile-friendly,age-10-plus"
)
