#!/usr/bin/env python3
"""Metadata for LAN Arcade native board-game intake."""
from __future__ import annotations

BOARD_GAMES = [
    dict(
        id="pioneers-lan", download_slug="pioneers", title="Pioneers LAN Table", short_title="Pioneers", icon="CATAN",
        meta="Native Board Game - Settlers-like",
        description="Offline Pioneers hub with cached packages, local server notes, and no-internet client/server/AI play proof.",
        tags="Board Game,Strategy,Native", categories="board-game,strategy,multiplayer,family,casual,age-10-plus",
        eyebrow="Board game - playable smoke passed",
        lede="A Settlers of Catan-style local board game: gather resources, build roads and settlements, trade, and race for victory points on a LAN-hosted table.",
        facts=["Catan-like", "Local server", "AI opponents", "No-internet smoke passed"],
        source="https://pio.sourceforge.net/", packages=["pioneers", "pioneers-console", "pioneers-data"],
        docs=dict(dest="pioneers-site", pages=["https://pio.sourceforge.net/", "https://pio.sourceforge.net/manual/"]),
        screenshot="qa/reports/board-game-exploratory/pioneers-play-file-20260618T160722Z/after-input.png",
        status_class="pass",
        qa_summary="PASS: bwrap no-internet namespace, local pioneers-server-console, three AI players, one GUI client named LANSmoke, board state and AI building activity captured.",
        cards=[
            ("Why play", "This is the clearest family-table win in the batch: it has the Catan rhythm, works offline, and fills a slow multiplayer strategy slot."),
            ("What the smoke proved", "The VM hosted a local server with three AIs, connected a GUI client, and captured active board/chat state without external network access."),
            ("How to host", "Install the cached packages, then start a server with a packaged .game file such as default.game."),
        ],
        steps=[
            ("Place settlements", "Starting positions decide your resource flow; roads and settlements are the spine of the game."),
            ("Watch dice and scarcity", "Resource rolls decide what you can build, so trade and ports matter when dice are unkind."),
            ("Build toward points", "Settlements, cities, roads, and development cards push you toward the win condition."),
            ("Use AI for first tests", "The local smoke uses AIs so one person can verify the table before real players join."),
        ],
        status=[("Offline play smoke", "Passed"), ("Server mode", "Local server + AIs"), ("Internet dependency", "None during smoke"), ("Next gate", "Two real LAN devices")],
    ),
    dict(
        id="teg-lan", download_slug="teg", title="TEG LAN Table", short_title="TEG", icon="TEG",
        meta="Native Board Game - Risk-like",
        description="Offline TEG hub with cached package shelf and no-internet local server, bots, and GUI client smoke proof.",
        tags="Board Game,Strategy,Native", categories="board-game,strategy,multiplayer,tactical,age-10-plus",
        eyebrow="Board game - playable smoke passed",
        lede="A Risk-like world-conquest board game with territories, armies, cards, alliances of convenience, and LAN/server play.",
        facts=["Risk-like", "Dedicated server", "Bots", "No-internet smoke passed"],
        source="https://github.com/wfx/teg", packages=["teg"], docs=dict(dest="teg-site", pages=["https://github.com/wfx/teg"]),
        screenshot="qa/reports/board-game-exploratory/teg-play-robots-20260618T161317Z/after-color.png",
        status_class="pass",
        qa_summary="PASS: bwrap no-internet namespace, tegserver with metaserver disabled, five tegrobots, GUI client joined and selected a colour; bot/player status and chat captured.",
        cards=[
            ("Why play", "A classic territory-control slot with real multiplayer bones and enough bots for solo smoke testing."),
            ("What the smoke proved", "A local server ran without the metaserver, five bots joined, and the GUI client reached an active world map/player state offline."),
            ("Player fit", "Best for people who like Risk-style expansion, dice battles, temporary treaties, and long grudges."),
        ],
        steps=[
            ("Pick a colour", "Join the table, choose a colour, and wait for all seats/bots to be ready."),
            ("Expand carefully", "Every attack opens a border; overextending is how a strong position collapses."),
            ("Use cards and continents", "Card rewards and continent bonuses are the swing mechanics to watch."),
            ("Disable metaserver offline", "For LAN Arcade testing, start tegserver with the metaserver disabled and connect locally."),
        ],
        status=[("Offline play smoke", "Passed"), ("Server mode", "tegserver + bots"), ("Internet dependency", "Metaserver disabled"), ("Next gate", "Two real LAN clients")],
    ),
    dict(
        id="ksirk-lan", download_slug="ksirk", title="KsirK Local Risk Table", short_title="KsirK", icon="KSRK",
        meta="Native Board Game - Risk-like",
        description="Offline KsirK hub with cached package shelf, KDE docs, and no-internet new local game smoke proof.",
        tags="Board Game,Strategy,Native", categories="board-game,strategy,tactical,family,age-10-plus",
        eyebrow="Board game - playable smoke passed",
        lede="A KDE Risk-style conquest game with local play, themed maps, armies to place, and a classic world-domination board-game loop.",
        facts=["Risk-like", "Local play", "KDE game", "No-internet smoke passed"],
        source="https://apps.kde.org/ksirk/", packages=["ksirk"],
        docs=dict(dest="ksirk-site", pages=["https://apps.kde.org/ksirk/", "https://docs.kde.org/stable5/en/ksirk/ksirk/"]),
        screenshot="qa/reports/board-game-exploratory/ksirk-started-20260618T162036Z/started.png",
        status_class="pass",
        qa_summary="PASS: bwrap no-internet namespace, KsirK launched through the local-game wizard and reached an actual board with armies to place.",
        cards=[
            ("Why play", "The polished local Risk-like option: no server required for first play, clear board visuals, and easy hot-seat style testing."),
            ("What the smoke proved", "The VM created a local game and reached the map/army placement state in a no-internet namespace."),
            ("Caution", "This is more local/hot-seat oriented than TEG. For LAN-style multiplayer proof, TEG is currently stronger."),
        ],
        steps=[
            ("Create local game", "Use New Local Game and pick the default Earth-style skin for the first run."),
            ("Place armies", "The first real decision is where to put your starting armies before attacks begin."),
            ("Read the goal", "KsirK can assign goals, so check the objective prompt instead of assuming total conquest."),
            ("Use as a low-friction table", "This is a good one-machine strategy option before setting up multiple clients."),
        ],
        status=[("Offline play smoke", "Passed"), ("Server mode", "Local game"), ("Internet dependency", "None during smoke"), ("Next gate", "Human playthrough")],
    ),
    dict(
        id="atlantik-lan", download_slug="atlantik", title="Atlantik / monopd Table", short_title="Atlantik", icon="ATL",
        meta="Native Board Game - Monopoly-like",
        description="Offline Atlantik hub with cached GTK client/server packages and a documented local-server partial smoke requiring two players for board start.",
        tags="Board Game,Strategy,Native", categories="board-game,strategy,multiplayer,family,casual,age-10-plus",
        eyebrow="Board game - partial smoke",
        lede="A Monopoly-like GTK client for the monopd board-game server. It can connect to a local server offline, but a full board start needs at least two players.",
        facts=["Monopoly-like", "monopd server", "Two-player required", "Partial smoke"],
        source="http://gtkatlantic.gradator.net/", packages=["gtkatlantic", "monopd"], docs=dict(dest="atlantik-site", pages=["http://gtkatlantic.gradator.net/"]),
        screenshot="qa/reports/board-game-exploratory/atlantik-start-game-20260618T163830Z/02-after-start.png",
        status_class="partial",
        qa_summary="PARTIAL: bwrap no-internet namespace, socket-activated monopd on 127.0.0.1:1234, GTK client connected and created a game lobby; board start requires at least two players.",
        cards=[
            ("Why play", "The closest clean Monopoly-style candidate in Debian, with an actual client/server architecture."),
            ("What the smoke proved", "The default client tried the internet metaserver, but the direct local server path worked offline using socket activation."),
            ("Why not green yet", "Starting the board with one automated client returns: this game requires at least 2 players. It needs a two-client smoke before promotion."),
        ],
        steps=[
            ("Start local server", "Use systemd socket activation or the packaged monopd.socket so clients connect on port 1234."),
            ("Avoid metaserver", "The public server list/metaserver is internet-bound; use Game > Connect to server and enter GannanNet/local host."),
            ("Create a game", "Create the Monopoly game, then add a second real client before pressing Start game."),
            ("Promotion gate", "Needs two GUI clients in one LAN game and an actual board screenshot."),
        ],
        status=[("Offline play smoke", "Partial"), ("Server mode", "monopd socket activation"), ("Internet dependency", "Metaserver avoided"), ("Next gate", "Two-client board start")],
    ),
    dict(
        id="triplea-lan", download_slug="triplea", title="TripleA Offline Candidate", short_title="TripleA", icon="AAA",
        meta="Native Board Game - Axis & Allies-like",
        description="TripleA candidate hub with cached Debian package/map asset and a visible blocker: offline launch still attempts GitHub/update/map checks before a local map is playable.",
        tags="Board Game,Strategy,Native", categories="board-game,strategy,multiplayer,tactical,age-10-plus",
        eyebrow="Board game - blocker found",
        lede="A large Axis & Allies-style strategy engine with many maps and scenarios. It is promising, but the VM smoke caught online update/map checks that block clean offline promotion.",
        facts=["Axis & Allies-like", "Large map engine", "Update check blocker", "Not promoted"],
        source="https://triplea-game.org/", packages=["triplea"], docs=dict(dest="triplea-site", pages=["https://triplea-game.org/", "https://triplea-game.org/user-guide/"]),
        screenshot="qa/reports/board-game-exploratory/triplea-bwrap-offline-map-20260618T160351Z/after-return.png",
        status_class="blocked",
        qa_summary="BLOCKED: bwrap no-internet namespace showed TripleA attempting GitHub/raw.githubusercontent.com update/map checks; local map cache was not enough to reach a playable Start Local Game state.",
        cards=[
            ("Why it matters", "TripleA would be the heavyweight board-war slot, and Dylan already recognised it as a strong candidate."),
            ("What failed", "In offline smoke it tried GitHub/raw.githubusercontent.com for updates and map metadata, then left Start Local Game unavailable."),
            ("Safe next action", "Patch/configure update and map-list behaviour, prove local maps are recognised, then run a full first-turn smoke."),
        ],
        steps=[
            ("Do not call it playable", "The package launches, but the smoke found online dependency behaviour before real local play."),
            ("Cache maps explicitly", "The World War II Classic map ZIP is cached, but TripleA still needs to recognise local maps offline."),
            ("Patch update checks", "Disable or redirect startup update/map checks for the LAN Arcade environment."),
            ("Promotion gate", "Start a local map, make at least one first-turn action, and capture that under no-internet conditions."),
        ],
        status=[("Offline play smoke", "Blocked"), ("Server mode", "Not tested"), ("Internet dependency", "GitHub/map checks found"), ("Next gate", "Patch + first turn")],
    ),
    dict(
        id="biloba-lan", download_slug="biloba", title="Biloba Local Table", short_title="Biloba", icon="BILO",
        meta="Native Board Game - Abstract Strategy",
        description="No-internet smoked abstract strategy board game with local two-player board proof and cached Debian packages.",
        tags="Board Game,Strategy,Native", categories="board-game,strategy,family,casual,age-10-plus",
        eyebrow="Board game - playable smoke passed",
        lede="An abstract strategy board game for two to four players: move, jump, capture, and keep enough pieces alive to stay in the match.",
        facts=["Abstract strategy", "2-4 players", "Local play", "No-internet smoke passed"],
        source="https://biloba.sourceforge.net/", packages=["biloba", "biloba-data"], docs=dict(dest="biloba-site", pages=["https://biloba.sourceforge.net/"]),
        screenshot="qa/reports/native-board-game-expanded/biloba-play-20260618T185846Z/03-after-board-input.png",
        status_class="pass",
        qa_summary="PASS: bwrap no-internet namespace, Biloba launched, Play was clicked, and the screenshot shows an actual board with pieces and player-turn text.",
        cards=[
            ("Why play", "A compact abstract table game: quick to launch, rules are different from chess/checkers, and it supports more than two players."),
            ("What the smoke proved", "The VM reached a live board state with pieces and player-turn text under no-internet isolation."),
            ("Player fit", "Good for people who like tactical capture games and want something less familiar than chess or Risk."),
        ],
        steps=[
            ("Start local play", "Use Play from the setup screen for the first offline test."),
            ("Move and jump", "Pieces move to adjacent spaces or jump over pieces; captures are positional."),
            ("Watch mandatory captures", "If a capture is available, the game expects you to resolve it."),
            ("Network later", "The package includes network support, but the current green gate is local board play."),
        ],
        status=[("Offline play smoke", "Passed"), ("Server mode", "Local play proven"), ("Internet dependency", "None during smoke"), ("Next gate", "Network two-client test")],
    ),
    dict(
        id="ricochet-lan", download_slug="ricochet", title="Ricochet Robots LAN", short_title="Ricochet", icon="RICO",
        meta="Native Board Game - Puzzle Race",
        description="No-internet smoked Ricochet Robots server/client setup with rrserve and a local client reaching the puzzle board.",
        tags="Board Game,Puzzle,Native", categories="board-game,puzzle,multiplayer,tactical,family,age-10-plus",
        eyebrow="Board game - playable smoke passed",
        lede="A multiplayer Ricochet Robots table: solve robot movement puzzles on a shared board, bid a move count, then prove the route.",
        facts=["Ricochet Robots", "Local server", "Puzzle race", "No-internet smoke passed"],
        source="http://rr.nickle.org", packages=["ricochet"], docs=dict(dest="ricochet-site", pages=["http://rr.nickle.org"]),
        screenshot="qa/reports/native-board-game-expanded/ricochet-server-20260618T185709Z/02-after-input.png",
        status_class="pass",
        qa_summary="PASS: bwrap no-internet namespace, rrserve ran locally and the Ricochet client joined a named game and reached an active puzzle board.",
        cards=[
            ("Why play", "A strong board-game-night slot that is quick, brainy, and multiplayer without being a war game."),
            ("What the smoke proved", "A local rrserve instance accepted the client and displayed the active board offline."),
            ("Player fit", "Best for puzzle-solvers who enjoy racing to find the shortest route."),
        ],
        steps=[
            ("Start rrserve", "Run the packaged server on the LAN Arcade host or a local machine."),
            ("Join by name", "Clients connect to the server and join or create the same game name."),
            ("Bid a route", "Find the shortest robot path, bid your move count, then execute it."),
            ("Use one-at-a-time hosting", "The server is lightweight, but keep it in the normal on-demand service pattern."),
        ],
        status=[("Offline play smoke", "Passed"), ("Server mode", "rrserve + client"), ("Internet dependency", "None during smoke"), ("Next gate", "Two real LAN clients")],
    ),
    dict(
        id="bovo-lan", download_slug="bovo", title="Bovo Gomoku", short_title="Bovo", icon="BOVO",
        meta="Native Board Game - Gomoku",
        description="No-internet smoked KDE Gomoku/Five-in-a-row game with actual stones placed on the board.",
        tags="Board Game,Strategy,Native", categories="board-game,strategy,family,casual,age-10-plus",
        eyebrow="Board game - playable smoke passed",
        lede="A clean Gomoku table: place X and O stones on a grid and race to make five in a row.",
        facts=["Gomoku", "Quick local play", "KDE game", "No-internet smoke passed"],
        source="https://apps.kde.org/bovo/", packages=["bovo"], docs=dict(dest="bovo-site", pages=["https://apps.kde.org/bovo/"]),
        screenshot="qa/reports/native-board-game-expanded/bovo-board-20260618T185120Z/02-after-input.png",
        status_class="pass",
        qa_summary="PASS: bwrap no-internet namespace, Bovo launched and the screenshot shows multiple X/O stones after input.",
        cards=[("Why play", "Tiny, fast, and understandable in ten seconds."), ("What the smoke proved", "The board accepted moves and displayed active stones offline."), ("Player fit", "Good lightweight fallback for old laptops and quick family rounds.")],
        steps=[("Start a game", "Open Bovo and begin from the default board."), ("Place stones", "Take turns placing stones on grid intersections."), ("Make five", "Create five in a row while blocking the opponent."), ("Use difficulty", "The bottom difficulty selector changes computer strength.")],
        status=[("Offline play smoke", "Passed"), ("Server mode", "Local play"), ("Internet dependency", "None during smoke"), ("Next gate", "Human playthrough")],
    ),
    dict(
        id="kfourinline-lan", download_slug="kfourinline", title="KFourInLine", short_title="KFourInLine", icon="4IN",
        meta="Native Board Game - Connect Four",
        description="No-internet smoked Connect Four game with a started game and visible piece drop.",
        tags="Board Game,Strategy,Native", categories="board-game,strategy,family,casual,age-5-plus",
        eyebrow="Board game - playable smoke passed",
        lede="A Connect Four table: drop pieces into columns and race to connect four before the opponent does.",
        facts=["Connect Four", "Local play", "KDE game", "No-internet smoke passed"],
        source="https://apps.kde.org/kfourinline/", packages=["kfourinline"], docs=dict(dest="kfourinline-site", pages=["https://apps.kde.org/kfourinline/"]),
        screenshot="qa/reports/native-board-game-expanded/kfourinline-play-20260618T185425Z/02-after-input.png",
        status_class="pass",
        qa_summary="PASS: bwrap no-internet namespace, Easy Game was clicked and the screenshot shows a running game with a dropped piece.",
        cards=[("Why play", "A low-friction family classic and a good young-kids board slot."), ("What the smoke proved", "The quick-launch flow entered a running game and accepted a move offline."), ("Player fit", "Best as a quick two-player or computer-opponent table.")],
        steps=[("Pick a mode", "Use Easy, Normal, Hard, or Two Player from the quick launcher."), ("Drop pieces", "Click a column to drop a piece."), ("Connect four", "Horizontal, vertical, and diagonal lines count."), ("Reset quickly", "Use New or End Game when switching players.")],
        status=[("Offline play smoke", "Passed"), ("Server mode", "Local play"), ("Internet dependency", "None during smoke"), ("Next gate", "Mobile/laptop client notes")],
    ),
    dict(
        id="kreversi-lan", download_slug="kreversi", title="KReversi", short_title="KReversi", icon="REV",
        meta="Native Board Game - Reversi",
        description="No-internet smoked Reversi/Othello game with game started, pieces flipped, and turn status visible.",
        tags="Board Game,Strategy,Native", categories="board-game,strategy,family,casual,age-10-plus",
        eyebrow="Board game - playable smoke passed",
        lede="A Reversi/Othello table: place discs, flip the opponent's line, and own the board by the end.",
        facts=["Reversi", "Local play", "KDE game", "No-internet smoke passed"],
        source="https://apps.kde.org/kreversi/", packages=["kreversi"], docs=dict(dest="kreversi-site", pages=["https://apps.kde.org/kreversi/"]),
        screenshot="qa/reports/native-board-game-expanded/kreversi-play-20260618T185425Z/02-after-input.png",
        status_class="pass",
        qa_summary="PASS: bwrap no-internet namespace, game started and the screenshot shows active discs, score, and turn text.",
        cards=[("Why play", "Classic strategy with simple rules and real tactical depth."), ("What the smoke proved", "The VM got beyond setup into a live game state offline."), ("Player fit", "Good for quick thinking games without a long rules explanation.")],
        steps=[("Start game", "Use the default computer opponent for the first offline test."), ("Place legally", "A move must trap one or more opponent discs in a line."), ("Flip discs", "Captured lines become your color."), ("Win the count", "Most discs at the end wins.")],
        status=[("Offline play smoke", "Passed"), ("Server mode", "Local play"), ("Internet dependency", "None during smoke"), ("Next gate", "Human playthrough")],
    ),
    dict(
        id="kigo-lan", download_slug="kigo", title="Kigo + GNU Go", short_title="Kigo", icon="GO",
        meta="Native Board Game - Go",
        description="No-internet smoked Go client with local GNU Go engine, game start, engine reply, and move list proof.",
        tags="Board Game,Strategy,Native", categories="board-game,strategy,tactical,family,age-10-plus",
        eyebrow="Board game - playable smoke passed",
        lede="A Go table with a local engine: place stones, build territory, capture groups, and learn on a smaller 9x9 board first.",
        facts=["Go", "GNU Go engine", "9x9 quick start", "No-internet smoke passed"],
        source="https://apps.kde.org/kigo/", packages=["kigo", "gnugo"], docs=dict(dest="kigo-site", pages=["https://apps.kde.org/kigo/", "https://www.gnu.org/software/gnugo/"]),
        screenshot="qa/reports/native-board-game-expanded/kigo-play-20260618T185425Z/02-after-input.png",
        status_class="pass",
        qa_summary="PASS: bwrap no-internet namespace, Kigo started a 9x9 game, GNU Go replied, and the move list shows real moves.",
        cards=[("Why play", "A deep classic that scales from short 9x9 learning games to full 19x19 play."), ("What the smoke proved", "The local engine works offline and responds inside the GUI."), ("Player fit", "Best for strategy players who want a long-term skill game.")],
        steps=[("Start small", "Use Tiny 9x9 until players understand territory and captures."), ("Play against GNU Go", "The local engine is installed and does not need the internet."), ("Read the move list", "Kigo shows moves and turn status on the right."), ("Scale later", "Move to 13x13 or 19x19 once games are comfortable.")],
        status=[("Offline play smoke", "Passed"), ("Server mode", "Local engine"), ("Internet dependency", "None during smoke"), ("Next gate", "Human teaching notes")],
    ),
    dict(
        id="pentobi-lan", download_slug="pentobi", title="Pentobi", short_title="Pentobi", icon="BLOK",
        meta="Native Board Game - Blokus-like",
        description="No-internet smoked Blokus-like strategy game with an active board and pieces placed.",
        tags="Board Game,Strategy,Native", categories="board-game,strategy,tactical,family,casual,age-10-plus",
        eyebrow="Board game - playable smoke passed",
        lede="A Blokus-like polyomino placement game: fit awkward pieces onto the board while blocking space from your opponent.",
        facts=["Blokus-like", "Local play", "Piece placement", "No-internet smoke passed"],
        source="https://pentobi.sourceforge.io", packages=["pentobi"], docs=dict(dest="pentobi-site", pages=["https://pentobi.sourceforge.io"]),
        screenshot="qa/reports/native-board-game-expanded/pentobi-board-20260618T185120Z/02-after-input.png",
        status_class="pass",
        qa_summary="PASS: bwrap no-internet namespace, Pentobi launched and the screenshot shows an active board with placed pieces.",
        cards=[("Why play", "Good spatial strategy and much easier to explain than a large war game."), ("What the smoke proved", "The GUI reached an active game state and accepted board input offline."), ("Player fit", "Great for puzzle-minded players and family board-game sessions.")],
        steps=[("Choose pieces", "Pick from the piece rack on the right."), ("Place by corners", "Blokus-style games usually grow by touching corners, not edges."), ("Block space", "Deny future placement space while keeping your own options open."), ("Use undo/redo", "The toolbar makes short learning games forgiving.")],
        status=[("Offline play smoke", "Passed"), ("Server mode", "Local play"), ("Internet dependency", "None during smoke"), ("Next gate", "Human playthrough")],
    ),
    dict(
        id="gnubg-lan", download_slug="gnubg", title="GNU Backgammon", short_title="GNU Backgammon", icon="BG",
        meta="Native Board Game - Backgammon",
        description="No-internet smoked GNU Backgammon GUI with board, players, score, and match state visible.",
        tags="Board Game,Strategy,Native", categories="board-game,strategy,family,casual,age-10-plus",
        eyebrow="Board game - playable smoke passed",
        lede="A strong backgammon client with analysis tools, computer play, match records, and a traditional race-and-hit board loop.",
        facts=["Backgammon", "Analysis tools", "Local play", "No-internet smoke passed"],
        source="https://www.gnu.org/software/gnubg/", packages=["gnubg", "gnubg-data"], docs=dict(dest="gnubg-site", pages=["https://www.gnu.org/software/gnubg/"]),
        screenshot="qa/reports/native-board-game-expanded/gnubg-board-20260618T185120Z/02-after-input.png",
        status_class="pass",
        qa_summary="PASS: bwrap no-internet namespace, GNU Backgammon GUI launched with board, players, score, and match state visible.",
        cards=[("Why play", "Classic dice-and-strategy board game with a very mature engine."), ("What the smoke proved", "The GUI opens offline and shows a live board/match state."), ("Caution", "The visual theme is old-school and the first board screenshot is cramped; usability pass is still worth doing.")],
        steps=[("Start a match", "Use New from the toolbar or menu."), ("Roll and move", "Move checkers according to dice while blocking and hitting."), ("Bear off", "Race all pieces home and off the board."), ("Use analysis later", "GNU Backgammon can review moves, but first gate is just playable offline matches.")],
        status=[("Offline play smoke", "Passed"), ("Server mode", "Local play"), ("Internet dependency", "None during smoke"), ("Next gate", "Usability/theme check")],
    ),
    dict(
        id="knavalbattle-lan", download_slug="knavalbattle", title="KNavalBattle", short_title="KNavalBattle", icon="SHIP",
        meta="Native Board Game - Battleship",
        description="Partial no-internet smoke for Battleship: single-player setup and ship placement works, but a full firing turn still needs automation.",
        tags="Board Game,Strategy,Native", categories="board-game,strategy,multiplayer,family,casual,age-10-plus",
        eyebrow="Board game - partial smoke",
        lede="A Battleship table with single-player and network options. Current evidence reaches ship placement; full battle-turn proof is still pending.",
        facts=["Battleship", "Single-player setup", "Network option", "Partial smoke"],
        source="https://apps.kde.org/knavalbattle/", packages=["knavalbattle"], docs=dict(dest="knavalbattle-site", pages=["https://apps.kde.org/knavalbattle/"]),
        screenshot="qa/reports/native-board-game-expanded/knavalbattle-play-20260618T185425Z/02-after-input.png",
        status_class="partial",
        qa_summary="PARTIAL: bwrap no-internet namespace, KNavalBattle entered single-player setup and placed a ship; a full battle/firing turn still needs proof.",
        cards=[("Why play", "Classic Battleship is familiar, kid-friendly, and can be networked later."), ("What the smoke proved", "Single-player setup and first ship placement work offline."), ("Why not green yet", "The smoke did not finish ship placement and fire a battle turn.")],
        steps=[("Single player first", "Click Single Player for the simplest offline path."), ("Place ships", "Use left click to place and right click to rotate."), ("Start battle", "After all ships are placed, fire on the opponent grid."), ("Promotion gate", "Automate a complete setup plus first shot or test it manually with screenshots.")],
        status=[("Offline play smoke", "Partial"), ("Server mode", "Single-player setup"), ("Internet dependency", "None during smoke"), ("Next gate", "First battle turn")],
    ),
    dict(
        id="xfrisk-lan", download_slug="xfrisk", title="XFrisk Risk Table", short_title="XFrisk", icon="RISK",
        meta="Native Board Game - Risk-like",
        description="Partial no-internet smoke for XFrisk: helper started server, AIs, and client, but automation stopped at setup before a turn.",
        tags="Board Game,Strategy,Native", categories="board-game,strategy,multiplayer,tactical,age-10-plus",
        eyebrow="Board game - partial smoke",
        lede="Another Risk-like table with a local server, AI players, and an X11 client. It is promising but needs a start-game/turn automation pass.",
        facts=["Risk-like", "Local server", "AI players", "Partial smoke"],
        source="https://www.tuxick.net/xfrisk/", packages=["xfrisk"], docs=dict(dest="xfrisk-site", pages=["https://www.tuxick.net/xfrisk/"]),
        screenshot="qa/reports/native-board-game-expanded/xfrisk-risk-20260618T185709Z/02-after-input.png",
        status_class="partial",
        qa_summary="PARTIAL: bwrap no-internet namespace, risk helper started friskserver, AIs, and xfrisk client; the screenshot shows map/setup and registered clients, but no actual turn yet.",
        cards=[("Why play", "A second Risk-like option with an old but functional local server/client design."), ("What the smoke proved", "The local server and AI/client registration work offline."), ("Why not green yet", "The smoke still needs to click through start game and capture a real turn.")],
        steps=[("Use risk helper", "The packaged risk command starts server, AIs, and client for a quick local game."), ("Add/start players", "The setup dialog must start the game before turns begin."), ("Play a turn", "Attack, move, or end turn once territories are assigned."), ("Promotion gate", "Automate start game plus first turn or test manually with screenshots.")],
        status=[("Offline play smoke", "Partial"), ("Server mode", "friskserver + AIs + xfrisk"), ("Internet dependency", "None during smoke"), ("Next gate", "Start-game and first turn")],
    ),

]

BY_ID = {game["id"]: game for game in BOARD_GAMES}
BY_DOWNLOAD_SLUG = {game["download_slug"]: game for game in BOARD_GAMES}
